### ISSUE TITLE
Release 4.1.1 doesn't show files in bonsai.

### ISSUE THREAD

**Issue by jBRNDnl** [sensu-plugins/sensu-plugins-network-checks#127]
Hi,

On https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-network-checks the following message reveals. 

This asset has compilation errors
Version 4.1.1: missing GitHub release asset for sensu-plugins-network-checks_4.1.1_centos_linux_amd64.tar.gz

It looks like the bonsai site failed coupling the github repo release to bonsai. Could you please help to use the latest again.

**Comment by nixwiz** [comment]
I have a PR open to fix this.
