### ISSUE TITLE
ping-check and metrics-ping is not working in 5.0.0

### ISSUE THREAD

**Issue by Boy-Sittisak** [sensu-plugins/sensu-plugins-network-checks#136]
I'm not sure if I did something wrong I just move from Sensu core to Sensu go
and I try to using this ping plugin but it not working

output for metrics-ping is "ping error: unable to ping"
output for ping-check is "CheckPING CRITICAL: ICMP ping unsuccessful for host: (successful: 0/1)"
but my old Sensu core server that still running with same plugin still able to ping without error but it version 4.0.0
I try to install version 4.0.0 plugin into Sensu go also not work

Did I miss anything?
Thank you ver much.

**Comment by nixwiz** [comment]
For what it's worth, I was able to create some simple checks for both metrics-ping.rb and check-ping.rb and they worked fine.  Given that, it's possibly not a code issue, could you please post this is a question on https://discourse.sensu.io ? We can work through troubleshooting there.  When you do post, please include configurations for your checks and assets, redacting any sensitive information.

**Comment by Boy-Sittisak** [comment]
Thank you very much, I research more and found the problem I never encounter before with permission with ping command in node I test. It working perfect now.
