### ISSUE TITLE
Checks with git merge comments in them

### ISSUE THREAD

**Issue by rmc3** [sensu-plugins/sensu-plugins-network-checks#2]
Several check files, such as metrics-netif.rb and check-rbl.rb, currently have merge comments in them. As such, they're probably not functional.

**Comment by mattyjones** [comment]
I will show this repo so love in the net 24hours.  Thanks for the tips!

**Comment by mattyjones** [comment]
@rmc3 if you have twitter hit me up on it at some point @devopsmatt or my email should be on the github page.

**Comment by rmc3** [comment]
Fixed by #4
