### ISSUE TITLE
metrics-ping.rb not working

### ISSUE THREAD

**Issue by maticmeznar** [sensu-plugins/sensu-plugins-network-checks#26]
Sensu version: 0.22.0. Plugin installed with `sensu-install` command.
```
sensu@a7cf7f839d7c:/$ metrics-ping.rb -c 1 -h localhost
Check failed to run: wrong argument type NilClass (must respond to :each), ["/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-network-checks-0.1.4/bin/metrics-ping.rb:79:in `zip'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-network-checks-0.1.4/bin/metrics-ping.rb:79:in `results'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-network-checks-0.1.4/bin/metrics-ping.rb:87:in `output'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-network-checks-0.1.4/bin/metrics-ping.rb:101:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

**Comment by eheydrick** [comment]
Which platform is this on? Do you get errors running any of the other plugins in network-checks? Do you get the error if you supply the full path to the script? e.g. `/opt/sensu/embedded/bin/metrics-ping.rb ...` Can you determine which ruby is running the check?

**Comment by maticmeznar** [comment]
I get the same error with full path to the script.
The script is running in a Debian Jessie Docker container.
Docker version is 1.10.
Host OS is CentOS 7 and Ubuntu 15.10 (same error on both).
I didn't check all metrics/check scripts from network-checks plugins, but those that I did are working fine, except `metrics-netif.rb` which requires `sar` to be installed.

Upon further investigation, Debian 8's `ping` command gives a slightly different output than `ping` under CentOS or Ubuntu 15.10.
```
debian8 $ ping -W1 -c1 localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.024 ms
--- localhost ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.024/0.024/0.024/0.000 ms
```
```
ubuntu1510 $ ping -W1 -c1 localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.038 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.038/0.038/0.038/0.000 ms
```
There is no `time 0ms` under Debian and some words in the output like `packets transmitted` are different.

**Comment by maticmeznar** [comment]
It seems `ping` is provided by different packages under Debian and Ubuntu. If I install "iputils-ping" on Debian 8, the metric-ping.rb works fine.

**Comment by eheydrick** [comment]
Interesting. That's crummy. Mind adding a note about the ping differences to the plugin? We should update the plugin to handle the different output as well.
