### ISSUE TITLE
metrics-ping.rb: pinging unresponsive host results in error

### ISSUE THREAD

**Issue by maticmeznar** [sensu-plugins/sensu-plugins-network-checks#30]
OS: Debian 8 (Jessie) under Docker 1.10 on CentOS 7 host.
Pinging an unresponsive host results in error (check failed to run) after the timeout expires. Pinging a responding host returns correct result. I tried with ping from `inetutils-ping` and `iputils-ping` packages, but the error seems the same for both.

```
root@ad4985f61de8:/# metrics-ping.rb --host 8.8.8.1
Check failed to run: undefined local variable or method `status' for #<PingMetrics:0x00000001ba2df8>, ["/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-network-checks-0.1.4/bin/metrics-ping.rb:95:in `validate'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-network-checks-0.1.4/bin/metrics-ping.rb:100:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

**Comment by eheydrick** [comment]
Can you give the version in master a shot. I fixed how it handles ping errors.

**Comment by maticmeznar** [comment]
@eheydrick LGTM, although I expected it would report 100% package loss for unresponsive hosts, not fail the check.
