### ISSUE TITLE
Failing Ping Checks - Check failed to run: No such file or directory

### ISSUE THREAD

**Issue by AirCombat** [sensu-plugins/sensu-plugins-network-checks#33]
Hi,

Intermittently, about 1 in every 15-20 checks I get this error when tring to ping. It does not seem to be related to network connectivity.

 `Check failed to run: No such file or directory - mtr, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-0.2.4/bin/check-ping.rb:101:in``'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-0.2.4/bin/check-ping.rb:101:in`run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]`

**Comment by eheydrick** [comment]
Hi @AirCombat, are you using the --report flag by chance? With the --report flag the plugin will run `mtr` to generate a report if pings fail. If you don't have `mtr` installed you'll get an error that it's missing.

**Comment by eheydrick** [comment]
Any updates?

**Comment by majormoses** [comment]
If we expect that something should be installed we should test that it is before using it and unknown if its not available.

**Comment by majormoses** [comment]
@AirCombat can you validate that #56 solves this issue for you?
