### ISSUE TITLE
cannot load such file -- net/ping (LoadError)

### ISSUE THREAD

**Issue by immusk** [sensu-plugins/sensu-plugins-network-checks#36]
I have sensu server and sensu-client Installed on one machine (centos) and installed the the plugins through gem.

Everything was good when I run the check_ping.rb from the command line, but When I configure the same check in /etc/sensu/conf.d/ and check in the UI I am getting this ruby issue;

gem install sensu-plugins-network-checks

and configured EMBEDDED_RUBY=true

when I check the UI the below is the error I am facing

/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:56:in `require': cannot load such file -- net/ping (LoadError)
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:56:in `require'
	from /opt/sensu/embedded/lib/ruby/2.3.0/gems/sensu-plugins-network-checks-0.2.4/bin/check-ping.rb:31:in `<main>'
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]

**Comment by eheydrick** [comment]
@immusk are you still experiencing problems running this plugin?

**Comment by immusk** [comment]
no @eheydrick, issue is resolved.

**Comment by RiRa12621** [comment]
so what was the fix then ?

**Comment by jsiddharth** [comment]
So what did you do to fix the issue ? Magically it wouldnt have disappeared right ?

**Comment by sansane123** [comment]
What is the fix here ?
