### ISSUE TITLE
metrics-netstat-tcp.rb fails when IPv6 is disabled

### ISSUE THREAD

**Issue by MattMencel** [sensu-plugins/sensu-plugins-network-checks#44]
Check failed to run: No such file or directory @ rb_sysopen - /proc/net/tcp6

I opened a PR to fix this.

**Comment by majormoses** [comment]
@MattMencel I don't see an open pr should this be closed?

**Comment by MattMencel** [comment]
Already merged...

https://github.com/sensu-plugins/sensu-plugins-network-checks/pull/45

**Comment by deepakdeore2004** [comment]
has this issue fixed? I am getting same error:

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.9 (Santiago)

`$ sudo /opt/sensu/embedded/bin/metrics-netstat-tcp.rb
Check failed to run: No such file or directory @ rb_sysopen - /proc/net/tcp6, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-network-checks-3.1.1/bin/metrics-netstat-tcp.rb:88:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-network-checks-3.1.1/bin/metrics-netstat-tcp.rb:88:in `open'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-network-checks-3.1.1/bin/metrics-netstat-tcp.rb:88:in `netstat'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-network-checks-3.1.1/bin/metrics-netstat-tcp.rb:114:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]`

**Comment by majormoses** [comment]
did you try to disable ipv6 with the option added in that PR? Please include the full command you are running.

**Comment by deepakdeore2004** [comment]
just tried "--disabletcp6" and it worked
