### ISSUE TITLE
Failed to convert timeout

### ISSUE THREAD

**Issue by sgiacomel** [sensu-plugins/sensu-plugins-network-checks#51]
Using ruby2.3.0 and sensu core 0.25.3 this check:
check-whois-domain-expiration-multi.rb -t 30 -w 60 -c 15 -d sensibill.io
fails with this error:
Check failed to run: undefined method `zero?' for "30":String, ["/opt/sensu/embedded/lib/ruby/2.3.0/timeout.rb:74:in `timeout'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/whois-3.6.3/lib/whois/client.rb:91:in `lookup'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-1.1.0/bin/check-whois-domain-expiration-multi.rb:86:in `block in expiration_results'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-1.1.0/bin/check-whois-domain-expiration-multi.rb:82:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-1.1.0/bin/check-whois-domain-expiration-multi.rb:82:in `expiration_results'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-1.1.0/bin/check-whois-domain-expiration-multi.rb:107:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.3.0/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]

It looks like converting the timeout to_i would solve the issue.
Also, it would be nice to have the same timeout option for check-whois-domain-expiration.rb

**Comment by majormoses** [comment]
@sgiacomel can you take a look at #53 and validate it solves your problem?

**Comment by sgiacomel** [comment]
Excellent! It works, thanks
