### ISSUE TITLE
Domain-expiration invalid date

### ISSUE THREAD

**Issue by ericlaflamme** [sensu-plugins/sensu-plugins-network-checks#59]
Hi all,

Is just me or .com domain can't be check anymore? Stop to work like 3-4 days ago for me.

```
Check failed to run: invalid date, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-1.1.0/bin/check-whois-domain-expiration.rb:77:in `parse'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-1.1.0/bin/check-whois-domain-expiration.rb:77:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:57:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```

I checked .ca, .us and they are still working fine. I checked a couple .com domain and they all failing.

**Comment by majormoses** [comment]
@ericlaflamme that is indeed very interesting, can you include the command with options (redact anything sensitive) so I can try replicating?

**Comment by ericlaflamme** [comment]
@majormoses Thanks for your comment. Here is my commands
~~~
/opt/sensu/embedded/bin/check-whois-domain-expiration.rb -d google.com
~~~
or, usely, I use custom critical time
~~~
/opt/sensu/embedded/bin/check-whois-domain-expiration.rb -d google.com -c 30
~~~

.ca example with answer
~~~
/opt/sensu/embedded/bin/check-whois-domain-expiration.rb -d google.ca
WhoisDomainExpirationCheck OK: google.ca expires on 04-28-2018 (274 days away)
~~~

**Comment by majormoses** [comment]
@ericlaflamme I just replicated, I would assume something has changed in the data that is being returned as we get this from the whois gem and it is locked on the patch version here: https://github.com/sensu-plugins/sensu-plugins-network-checks/blob/2.0.0/sensu-plugins-network-checks.gemspec#L36

**Comment by majormoses** [comment]
It looks like somehow that is returning nil:
```
$ bundle exec ./bin/check-whois-domain-expiration.rb --domain google.com
nil
Check failed to run: invalid date, ["/home/babrams/projects/personal/sensu/sensu-plugins-network-checks/bin/check-whois-domain-expiration.rb:78:in `parse'", "/home/babrams/projects/personal/sensu/sensu-plugins-network-checks/bin/check-whois-domain-expiration.rb:78:in `initialize'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `new'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```

**Comment by Evesy** [comment]
Issue has been opened for the same thing on the upstream whois-parser repo: https://github.com/weppos/whois-parser/issues/56

**Comment by majormoses** [comment]
You beat me to it I was looking for an issue, the parser though I think was moved out in 4.x version of this gem though.

**Comment by majormoses** [comment]
Which means we need the upstream fix and a version bump on that in order to resolve this.

**Comment by akatch** [comment]
Per the `whois` 4.0.0 changelog,

> The WHOIS parsers are no longer part of this repository, and they have been extracted into a separate repository at https://github.com/weppos/whois-parser.  
>
>The whois library is now simply a WHOIS client. If you want to use the parsing features, install the whois-ruby gem (that already defines whois as a dependency).

It looks like we just have to add the `whois-parser` gem to the gemspec for this check. Does that sound right @majormoses ?

**Comment by majormoses** [comment]
@akatch I validated that the same problem exists in the `whois-parser` last week which is why it needs to be fixed there first, then we can include it in our gemspec which should resolve this issue.

**Comment by majormoses** [comment]
closed via #60

**Comment by acaraion** [comment]
Hello guys!

May i reopen this issue, because i'm still having some issues with it. It looks like it was fixed for `.com` domains but not for `.biz` in my case.

```
check-whois-domain-expiration.rb -w 10 -c 5 -d pycoding.biz
Check failed to run: invalid date, ["/var/lib/gems/2.3.0/gems/sensu-plugins-network-checks-2.0.1/bin/check-whois-domain-expiration.rb:78:in `parse'", "/var/lib/gems/2.3.0/gems/sensu-plugins-network-checks-2.0.1/bin/check-whois-domain-expiration.rb:78:in `initialize'", "/var/lib/gems/2.3.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `new'", "/var/lib/gems/2.3.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```

Can you confirm please if it's working for you?

Many thanks!

**Comment by majormoses** [comment]
@ericlaflamme Let's open a new issue and link it. The scope of this issue is for `.com` domains. As there are many TLDs now I think we need to think of these with smaller scope.

**Comment by ericlaflamme** [comment]
@majormoses I guess you meant @acaraion ? 

Seems like the parser have a lot of work to be done:

https://github.com/weppos/whois-parser/issues

It doesn't mention biz but I guess an issue must be opened there.

**Comment by majormoses** [comment]
yup my bad. Yes we can open an issue here but someone needs to open an upstream issue and fix it upstream.
